development:
  adapter: postgresql
  encoding: utf8
  database: knowledge_development
  pool: 5
  username: knowledge
  password: knowledge

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: knowledge_test
  pool: 5
  username: knowledge
  password: knowledge

production:
  adapter: postgresql
  encoding: utf8
  database: knowledge_production
  pool: 5
  username: knowledge
  password: knowledge
