development:
  adapter: postgresql
  encoding: utf8
  database: knowledge_development
  pool: 5
  username: knowledge
  password: knowledge
  host:     <%= ENV['IP'] %>
  
test: &TEST
  adapter: postgresql
  encoding: utf8
  database: knowledge_test
  pool: 5
  username: knowledge
  password: knowledge
  host:     <%= ENV['IP'] %>
  
production:
  adapter: postgresql
  encoding: utf8
  database: knowledge_production
  pool: 5
  username: knowledge
  password: knowledge
  host:     <%= ENV['IP'] %>